version: '3'
services:
  api:
    build: .
    image: wurcsjson2svg-image
    container_name:  wurcsjson2svg-api
    ports:
      - "8082:1337"
    environment:
        - VIRTUAL_HOST=wurcsjson2svg.glycosmos.org
        - LETSENCRYPT_HOST=wurcsjson2svg.glycosmos.org
        - LETSENCRYPT_EMAIL=support@glycosmos.org
    restart: always
networks:
  default:
    external:
      name: webproxy
    
